django/ctf/urls.py
from django.conf.urls import url

from ctf.constants import UUID_REGEX
from ctf import views


app_name = 'ctf'

urlpatterns = [
    url('^$', views.index, name='index'),
    url(r'^game$', views.game, name='game'),
    url(r'^team$', views.CurrentTeam.as_view(), name='current_team'),
    url(r'^team/(?P<pk>\d+)$', views.Team.as_view(), name='team'),
    url(r'^submit_flag/({})$'.format(UUID_REGEX), views.submit_flag, name='submit_flag'),
    url(r'^start_window$', views.start_window, name='start_window'),
    url(r'^board$', views.board, name='scoreboard')
]

django/ctflex/urls.py
"""Route URLs to Views"""

from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from ctflex import settings
from ctflex.views import anonyomous_users_only
from ctflex.constants import APP_NAME, UUID_REGEX, API_NAMESPACE
from ctflex import views

app_name = APP_NAME

WINDOW_CODE_TOKEN = r'(?:(?P<window_codename>\w+)/)'

api_urls = [
    url(r'^submit_flag/(?P<prob_id>{})/$'.format(UUID_REGEX), views.submit_flag, name='submit_flag'),
    url(r'^unread_announcements/$', views.unread_announcements, name='unread_announcements'),
]

windowed_urls = [
    url(r'^game/{}?$'.format(WINDOW_CODE_TOKEN), views.game, name='game'),
    url(r'^news/{}?$'.format(WINDOW_CODE_TOKEN), views.announcements, name='announcements'),
    url(r'^scoreboard/{}?$'.format(WINDOW_CODE_TOKEN), views.board, name='scoreboard'),
]

misc_urls = [
    url('^$', views.index, name='index'),
    url(r'^start_timer/$', views.start_timer, name='start_timer'),
    url(r'^account/$', views.account, name='account'),
    url(r'^team/(?P<team_id>\d+)$', views.team_public_detail, name='team'),
    url(r'^learn/$', views.display_learn, name='learn'),
    url(r'^sponsors/$', views.sponsors, name='sponsors'),
    url(r'^about/$', views.about, name='about'),
    url(r'^prizes/$', views.prizes, name='prizes'),
    url(r'^chat/$', views.chat, name='chat'),
    url(r'^winners/$', views.winners, name='winners'),
    url(r'^tee/$', views.tee, name='tee'),
]

auth_urls = [
    url(r'^login/$', auth_views.login, name='login', kwargs={
        'template_name': 'ctflex/auth/login.html'
    }),

    url(r'^logout/$', auth_views.logout, name='logout', kwargs={
        'next_page': 'ctflex:logout_done',
    }),

    url(r'^logout/done/$', views.logout_done, name='logout_done'),

    url(r'^password_change/$', views.password_change, name='password_change', kwargs={
        'template_name': 'ctflex/auth/password_change.html',
        'post_change_redirect': 'ctflex:password_change_done',
    }),

    url(r'^password_change/done/$', views.password_change_done, name='password_change_done'),

    url(r'^password_reset/$', views.password_reset, name='password_reset', kwargs={
        'template_name': 'ctflex/auth/password_reset.html',
        'email_template_name': 'ctflex/email/password_reset.txt',
        'subject_template_name': 'ctflex/email/password_reset.subject.txt',
        'post_reset_redirect': 'ctflex:password_reset_done',
        'extra_email_context': {
            'support_email': settings.SUPPORT_EMAIL,
            'sitename': settings.SITENAME,
        },
    }),

    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done', kwargs={
        'template_name': 'ctflex/auth/password_reset_done.html',
    }),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm', kwargs={
            'template_name': 'ctflex/auth/password_reset_confirm.html',
            'post_reset_redirect': 'ctflex:password_reset_complete',
        }),

    url(r'^reset/done/$', views.password_reset_complete, name='password_reset_complete'),

    url(r'^register/$', views.register, name='register'),

    url(r'^register/done/$', views.register_done, name='register_done'),
]

urlpatterns = [
    url(r'', include(auth_urls)),
    url(r'', include(misc_urls)),
    url(r'', include(windowed_urls)),
    url(r'^api/', include(api_urls, namespace=API_NAMESPACE)),
]

django/pactf/urls.py
"""Route URLs to apps"""

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from ratelimit.decorators import ratelimit

import ctflex.views

handler404 = ctflex.views.handler_factory(404)  # page not found
handler500 = ctflex.views.handler_factory(500)  # internal server error
handler403 = ctflex.views.handler_factory(403)  # permission denied
handler402 = ctflex.views.handler_factory(401)  # bad request

admin.autodiscover()
admin.site.login = (
    ratelimit(key='ip', rate='1/s', method='POST', block=True)(
        ratelimit(key='ip', rate='10/h', method='POST', block=True)(
            admin.site.login)))

urlpatterns = [
    url(r'^{}/'.format(settings.ADMIN_URL_PATH), include(admin.site.urls), name='admin'),
    url(r'', include('pactf_web.urls')),
    url(r'', include('ctflex.urls')),
]

django/ctf/models.py
import re
import uuid
import random, string
from os.path import join
import importlib.machinery

from django.db import models
from django.conf import settings
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User, Group, Permission
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.contrib.postgres import fields as psql

import markdown2


# TODO(Yatharth): Write decorator to set dispatch_uid automatically
# TODO(Yatharth): Write helper so error of clean returns all validationerrors


@receiver(pre_save, dispatch_uid='ctf.pre_save_validate')
def pre_save_validate(sender, instance, *args, **kwargs):
    # validate only fixtures (`loaddata` causes `raw` to be True)"""
    # if kwargs.get('raw', False):
    instance.full_clean()


def gen_key(chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(20))

# region User Models (by wrapping)

class Team(models.Model):

    # Essential data
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40, unique=True)
    score = models.IntegerField(default=0)
    key = models.CharField(max_length=30, default=gen_key)

    # Extra data
    school = models.CharField(max_length=20, blank=True, default='None')

    def __str__(self):
        return "<Team #{} {!r}>".format(self.id, self.name)

    def timer(self, window=None):
        if window is None:
            window = Window.current()
        return Timer.objects.get(window=window, team=self)

    def has_timer(self, window=None):
        try:
            self.timer(window=window)
        except Timer.DoesNotExist:
            return False
        else:
            return True

    def has_active_timer(self):
        return self.has_timer() and self.timer().active()

    def can_view_problems(self, window=None):
        return self.has_timer(window=window) and self.timer(window=window).start <= timezone.now()

    def start_timer(self):
        assert not self.has_timer()

        timer = Timer(window=Window.current(), team=self)
        timer.save()


class Competitor(models.Model):
    """Represents a competitor 'profile'

    Django's User class's fields are shunned except for:

        username, password, is_active, is_staff, date_joined

    """

    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.PROTECT)

    # Shunned fields
    first_name = models.CharField("First name", max_length=30, blank=True)
    last_name = models.CharField("Last name", max_length=30, blank=True)
    email = models.EmailField("Email", unique=True)

    def __str__(self):
        return "<Competitor #{} {!r}>".format(self.id, self.user.username)


# endregion


# region Problem Models

# FIXME(Yatharth): Consider simplifying
class CtfProblem(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50)

    points = models.IntegerField()
    description = models.TextField(blank=True, null=True)
    description_html = models.TextField(editable=False)
    hint = models.TextField(default='')
    hint_html = models.TextField(editable=False, blank=True, null=True)

    grader = models.FilePathField(
        help_text="Basename of the grading script from PROBLEM_DIR",
        path=settings.PROBLEMS_DIR, recursive=True, match=r'^.*\.py$'
    )
    dynamic = models.FilePathField(
        help_text="Basename of the generator script in PROBLEM_DIR",
        path=settings.PROBLEMS_DIR, recursive=True, match=r'^.*\.py$',
        blank=True, null=True
    )
    # dict function instead of {} because of mutability
    deps = psql.JSONField(default=dict, blank=True)

    def __str__(self):
        return "<Problem #{} {!r}>".format(self.id, self.name)

    def grade(self, flag, team):
        if not flag:
            return False, "Empty flag"

        grader_path = join(settings.PROBLEMS_DIR, self.grader)
        # FIXME(Yatharth): Handle FileNotFound
        grader = importlib.machinery.SourceFileLoader('grader', grader_path).load_module()
        correct, message = grader.grade(team, flag)
        return correct, message

    # TODO(Cam): Markdown's safe_mode is deprecated; research safety
    @staticmethod
    def markdown_to_html(markdown):
        EXTRAS = ('fenced-code-blocks', 'smarty-pants', 'spoiler')

        html = markdown2.markdown(markdown, extras=EXTRAS, safe_mode='escape')
        return html

    def link_static(self, old_text):
        PATTERN = re.compile(r'''{% \s* ctfstatic \s+ (['"]) (?P<basename> (?:(?!\1).)+ ) \1 \s* (%})''', re.VERBOSE)
        REPLACEMENT = r'{}/{}/{{}}'.format(settings.PROBLEMS_STATIC_URL, self.id)
        REPLACER = lambda match: static(REPLACEMENT.format(match.group('basename')))

        new_text = PATTERN.sub(REPLACER, old_text)
        return new_text

    def process_html(self, html):
        return self.markdown_to_html(self.link_static(html))

    def clean(self):
        if not self.dynamic:
            if not self.description:
                raise ValidationError('Description must be provided for non-dynamic problems!')
            self.description_html = self.process_html(self.description)
        elif self.description:
            raise ValidationError('Description should be blank for dynamic problems')
        self.hint_html = self.process_html(self.hint)

    def generate_desc(self, team):
        if not self.dynamic:
            return self.description_html
        gen_path = join(settings.PROBLEMS_DIR, self.dynamic)
        gen = importlib.machinery.SourceFileLoader('gen', gen_path).load_module()
        desc = gen.generate(team)
        return self.process_html(desc)

class Submission(models.Model):
    """Records a flag submission attempt

    The `p_id` field exists in addition to the `problem` foreign key.
    This is so in order to handle deletion of problems while not deleting Submissions for historical reasons.
    This is not done with competitor and team as 1) IDs are less useful for deleted objects of such types and 2) they are linked with Users, which have an is_active property which is used instead of deletion.

    `team` exists for quick querying of whether someone in a particular competitor's team has solved a particular problem.
    """
    id = models.AutoField(primary_key=True)

    p_id = models.UUIDField()
    problem = models.ForeignKey(CtfProblem, on_delete=models.SET_NULL, null=True)
    competitor = models.ForeignKey(Competitor, on_delete=models.SET_NULL, null=True)
    team = models.ForeignKey(Team, on_delete=models.SET_NULL, null=True)

    time = models.DateTimeField(auto_now_add=True)
    flag = models.CharField(max_length=80)
    correct = models.NullBooleanField()

    def __str__(self):
        return "<Submission @{} problem={} competitor={}>".format(self.time, self.problem, self.competitor)

    def sync_problem(self):
        try:
            self.problem = CtfProblem.objects.get(pk=self.p_id)
        except CtfProblem.DoesNotExist:
            pass

    def sync_team(self):
        self.team = self.competitor.team

    def clean(self):
        self.sync_problem()
        self.sync_team()


# endregion


# region Config Models

# TODO: Consider dbsettings

# class SingletonModel(models.Model):
#     id = models.AutoField
#
#     class Meta:
#         abstract = True
#
#     def save(self, *args, **kwargs):
#         self.__class__.objects.exclude(id=self.id).delete()
#         super(SingletonModel, self).save(*args, **kwargs)
#
#     @classmethod
#     def load(cls):
#         try:
#             return cls.objects.get()
#         except cls.DoesNotExist:
#             return cls()
#
# class Config():
#     passs

# endregion


# region Timer Models

print_time = lambda time: time.astimezone(tz=None).strftime('%m-%d@%H:%M:%S')


class Window(models.Model):
    id = models.AutoField(primary_key=True)

    start = models.DateTimeField()
    end = models.DateTimeField()

    personal_timer_duration = models.DurationField()

    def __str__(self):
        return "<Window #{} {} – {}>".format(self.id, print_time(self.start), print_time(self.end))

    @staticmethod
    def active():
        try:
            Window.current()
        except Window.DoesNotExist:
            return False
        else:
            return True

    @staticmethod
    def current():
        now = timezone.now()
        return Window.objects.get(start__lte=now, end__gte=now)

    def validate_windows_dont_overlap(self):
        for window in Window.objects.exclude(id=self.id):
            if window.start <= self.end and self.start <= window.end:
                raise ValidationError("Window overlaps with {}".format(window))

    def validate_positive_timedelta(self):
        if self.start >= self.end:
            raise ValidationError("End is not after start")

    def clean(self):
        self.validate_positive_timedelta()
        self.validate_windows_dont_overlap()
        super().clean()


class Timer(models.Model):
    """Represent the time period in which a team can, for example, submit flags"""

    class Meta:
        unique_together = ('window', 'team',)

    id = models.AutoField(primary_key=True)

    window = models.ForeignKey(Window, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    start = models.DateTimeField(auto_now=True)
    end = models.DateTimeField(editable=False, blank=True)

    def __str__(self):
        return "<Timer #{} window=#{} team=#{} {} – {}>".format(
            self.id, self.window_id, self.team_id, print_time(self.start), print_time(self.end))

    def active(self):

django/ctflex/templates/ctflex/misc/about.html
{% extends 'ctflex/base/headered.template.html' %}

{% block title %}
  Team - {{ block.super }}
{% endblock %}

{% block header %}
  The {% include 'ctflex/text/title.txt' %} Team
{% endblock %}


{% block content %}
  <p>
    <emph>Information not available.</emph>
  </p>
{% endblock %}

django/ctflex/templates/ctflex/misc/announcements.html
{% extends 'ctflex/base/windowed.template.html' %}
{% load static from staticfiles %}
{% load humanize %}

{% block title %}
  News - {{ block.super }}
{% endblock %}

{% block header %}
  News
{% endblock %}

{% block extra_css %}
  {{ block.super }}
  <link href="{% static "ctflex/css/announcements.css" %}" rel="stylesheet">
{% endblock %}


{% block content %}
  {% if announcements %}
    {% for annonce in announcements %}
      <div class="announcement panel panel-default">

        <div class="panel-heading">
          <div class="container-fluid">
            <div class="pull-left">{{ annonce.title_html|safe }}</div>
            <div class="pull-right">
            <span title="{{ annonce.date|date:'g:i A e \o\n j F Y' }}">
              {{ annonce.date|naturaltime }}
            </span>
            </div>
          </div>
        </div>

        {% if annonce.problems.exists %}
          <div class="affected-problems panel-body">
            This announcement affects the following problems:
          <span>
            {% for prob in annonce.problems.all %}
              <a href="{% url 'ctflex:game' window_codename=window.codename %}#{{ prob.id }}"
                 class="label label-primary">
                {{ prob.name }}
              </a>
            {% endfor %}
          </span>
          </div>
          <hr>
        {% endif %}

        <div class="panel-body">
          {{ annonce.body_html|safe }}
        </div>

      </div>
    {% endfor %}
  {% else %}

    <p>
      <strong>There are no announcements for this round right now.</strong>
    </p>
    <p>
      You can look at announcements for other rounds using the dropdown above.
    </p>

  {% endif %}
{% endblock %}

django/ctflex/templates/ctflex/misc/comma.snippet.html
{% if not forloop.last %}{% ifequal forloop.revcounter 2 %}, and {% else %}, {% endifequal %}{% else %}{% endif %}

django/ctflex/templates/ctflex/misc/error.html
{% extends 'ctflex/base/headered.template.html' %}

{% block title %}
  Error - {{ block.super }}
{% endblock %}

{% block header %}
  Error {{ status_code }}
{% endblock %}


{% block content %}
  <p>
    <strong>We are very sorry about this. Our team is currently working to fix this issue as soon as possible.</strong>
  </p>
  <p>
    For more information, please go to our
    <a target="_blank" href="https://pactf.statuspage.io/">System Status</a> page.
  </p>
  <p>
    We thank you in advance for your patience.
  </p>

{% endblock %}

django/ctflex/templates/ctflex/misc/help.html
{% extends 'ctflex/base/headered.template.html' %}
{% load static from staticfiles %}
{% load ctflex %}

{% block title %}
  Learn — {{ block.super }}
{% endblock %}

{% block header %}
  Help!
{% endblock %}


{% block content %}
  <p>
    <strong>What kind of difficulty are you having?</strong> Click to expand the tab!
  </p>

  <div id="help-accordion" class="panel-group">
    <div class="panel panel-default">
      <div class="panel-heading clearfix" data-toggle="collapse"
           data-target="#help-1" data-parent="#help-accordion">
        I don't know where to start!
      </div>
      <div id="help-1" class="panel-collapse collapse">
        <div class="panel-body">
          <p>
            That’s okay! Step back and look at the problem.
            Read the hint too—that’s what they’re there for! Next, think
            about what you really need to do. Do you need to do some complicated
            math for decryption? Do you need to get a site to tell you something
            secret? Figure it out, and get googling! We’re not that creative;
            you’d be surprised at what you can turn up.
          </p>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading clearfix" data-toggle="collapse"
           data-target="#help-2" data-parent="#help-accordion">
        Google isn’t helpful! What do I search for?
      </div>
      <div id="help-2" class="panel-collapse collapse">
        <div class="panel-body">
          <p>
            Look <i>really</i> closely. Read the hint again, or start googling
            the title blindly. Even if you don’t get anything useful, you’ll
            be getting closer and closer to the solution by figuring out what
            <i>doesn’t</i> work. In the worst-case, take a break and try again in
            a few hours; maybe you’ll have had some insight!
          </p>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading clearfix" data-toggle="collapse"
           data-target="#help-3" data-parent="#help-accordion">
        … Nope! Still stuck.
      </div>
      <div id="help-3" class="panel-collapse collapse">
        <div class="panel-body">
          <p>
            Well, we’re (almost) always on our
            <a href=https://webchat.freenode.net/>freenode channel</a> at
            #pactf2. Drop on by, and maybe we’ll give you a hint!
          </p>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

django/ctflex/templates/ctflex/misc/incubating.html
{% extends 'ctflex/base/headered.template.html' %}

{% block title %}
  Incubating - {{ block.super }}
{% endblock %}

{% block header %}
  Incubating…
{% endblock %}


{% block content %}
  <p>
    <strong>This page is not ready yet.</strong>
    If you haven’t registered, <a href="{% url 'ctflex:register' %}">register now</a>!
    Otherwise, check back again when the competition <a href="{% url 'ctflex:index' %}">starts</a>.
  </p>
{% endblock %}

django/ctflex/templates/ctflex/misc/learn.html
{% extends 'ctflex/base/headered.template.html' %}
{% load static from staticfiles %}
{% load ctflex_ctf %}

{% block title %}
  Learn — {{ block.super }}
{% endblock %}

{% block header %}
  Help!
{% endblock %}


{% block content %}
  <p>
    <strong>What kind of difficulty are you having?</strong> Click to expand the tab!
  </p>

  <div id="help-accordion" class="panel-group">
    <div class="panel panel-default">
      <div class="panel-heading clearfix" data-toggle="collapse"
           data-target="#help-1" data-parent="#help-accordion">
        I don't know where to start!
      </div>
      <div id="help-1" class="panel-collapse collapse">
        <div class="panel-body">
          <p>
            That’s okay! Step back and look at the problem.
            Read the hint too—that’s what they’re there for! Next, think
            about what you really need to do. Do you need to do some complicated
            math for decryption? Do you need to get a site to tell you something
            secret? Figure it out, and get googling! We’re not that creative;
            you’d be surprised at what you can turn up.
          </p>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading clearfix" data-toggle="collapse"
           data-target="#help-2" data-parent="#help-accordion">
        Google isn’t helpful! What do I search for?
      </div>
      <div id="help-2" class="panel-collapse collapse">
        <div class="panel-body">
          <p>
            Look <i>really</i> closely. Read the hint again, or start googling
            the title blindly. Even if you don’t get anything useful, you’ll
            be getting closer and closer to the solution by figuring out what
            <i>doesn’t</i> work. In the worst-case, take a break and try again in
            a few hours; maybe you’ll have had some insight!
          </p>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading clearfix" data-toggle="collapse"
           data-target="#help-3" data-parent="#help-accordion">
        … Nope! Still stuck.
      </div>
      <div id="help-3" class="panel-collapse collapse">
        <div class="panel-body">
          <p>
            Well, we’re (almost) always on our
            <a href="{% url 'ctflex:chat' %}">freenode IRC channel</a> at
            #pactf. Drop on by, and maybe we’ll give you a hint!
          </p>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

django/ctflex/templates/ctflex/misc/prizes.html
{% extends 'ctflex/base/headered.template.html' %}

{% block title %}
  Prizes - {{ block.super }}
{% endblock %}

{% block header %}
  Prizes
{% endblock %}


{% block content %}
  <p>
    <emph>Information not available.</emph>
  </p>
{% endblock %}

django/ctflex/templates/ctflex/misc/ratelimited.html
{% extends 'ctflex/base/headered.template.html' %}

{% block title %}
  Rate-limited - {{ block.super }}
{% endblock %}

{% block header %}
  Slow down!
{% endblock %}


{% block content %}
  <p>
    Please slow down and try again later.
  </p>
{% endblock %}

django/ctflex/templates/ctflex/misc/sponsors.html
{% extends 'ctflex/base/headered.template.html' %}

{% block title %}
  Sponsors - {{ block.super }}
{% endblock %}

{% block header %}
  Sponsors
{% endblock %}


{% block content %}
  <p>
    <emph>Information not available.</emph>
  </p>
{% endblock %}

django/ctflex/templates/ctflex/misc/team.html
{% extends 'ctflex/base/headered.template.html' %}
{% load ctflex_ctf %}

{% block title %}
  Team Profile — {{ block.super }}
{% endblock %}

{% block header %}
  Team: {{ other_team.name }}
{% endblock %}

{% block content %}

  {% if team == other_team %}

    <p>
      <strong>You are viewing your team’s public profile.</strong>
      For information about your personal account (or to add competitors to your team),
      go to your <a href="{% url 'ctflex:account' %}">Account</a> page.
    </p>

    {% if other_team.standing != other_team.GOOD_STANDING %}
      <p>

        {% if other_team.standing == other_team.DISQUALIFIED_STANDING %}
          <strong>Your team has been disqualified;</strong> as such, it is ineligible for prizes.
        {% endif %}

        {% if other_team.standing == other_team.INVISIBLE_STANDING %}
          <strong>Your team has been disqualified;</strong> as such, it is ineligible for prizes
          and does not appear on any scoreboards.
        {% endif %}

        Please email <a href="mailto:{{ contact_email }}">{{ contact_email }}</a>
        if you have any questions.

      </p>
    {% endif %}

    <br>

  {% endif %}

  {% if team == other_team or other_team.standing != other_team.INVISIBLE_STANDING %}

    <div class="panel-group">
      <div class="panel panel-primary">
        <div class="panel-heading">
          Team Details
        </div>
        <ul class="list-group">
          <li class="list-group-item clearfix">
          <span class="bold">
            Team Name
          </span>
          <span class="pull-right">
            {{ other_team.name }}
          </span>
          </li>
          <li class="list-group-item clearfix">
          <span class="bold">
            School
          </span>
          <span class="pull-right">
            {{ other_team.school|default:"None" }}
          </span>
          </li>
          <li class="list-group-item clearfix">
          <span class="bold">
            Eligibility
          </span>
            for prizes
          <span class="pull-right">
            {% eligible other_team as is_eligible %}
            {% if is_eligible %}
              <span class="glyphicon glyphicon-color glyphicon-ok-sign"></span>
            {% else %}
              <span class="glyphicon glyphicon-color glyphicon-remove-sign"></span>
            {% endif %}
          </span>
          </li>
          <li class="list-group-item clearfix">
          <span class="bold">
            Members
          </span>
          <span class="pull-right">
              {% for competitor in other_team.competitor_set.all %}
                {{ competitor.user.username }}{% include 'ctflex/misc/comma.snippet.html' %}
              {% endfor %}
          </span>
          </li>
        </ul>
      </div>
    </div>

    <div class="panel-group">
      <div class="panel panel-primary">
        <div class="panel-heading">
          Scores<sup>†</sup>
        </div>
        <ul class="list-group">
          <li class="list-group-item list-group-item-info">
            <span class="bold">
              Overall<sup>‡</sup>
            </span>
            <span class="pull-right">
              {{ total_score }}
            </span>
          </li>
          {% for window in windows %}
            <li class="list-group-item">
            <span class="bold">
              {{ window.verbose_name }}
            </span>
              {{ window.start|date:"j F" }} – {{ window.end|date:"j F" }}
            <span class="pull-right">
              {% score team=other_team %}
            </span>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>

    <p>
      <sup>†</sup> Scores on this page are updated even after rounds have officially ended.
      Prizes will be awarded based on the relevant scoreboards.
    </p>
    <p>
      <sup>‡</sup> {% include 'ctflex/board/overall_explanation.snippet.html' %}
    </p>

  {% else %}

    <p>
      This team’s information cannot be displayed.
    </p>

  {% endif %}

{% endblock %}

django/ctflex/templates/ctflex/misc/tee.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Tee</title>
  <link href="{% static "ctflex/css/logo.css" %}" rel="stylesheet">
  <style>
    .logo-tee .outline {
{#      stroke: black;#}
    }

    .logo-tee .fill {
{#      fill: white;#}
    }
  </style>
</head>
<body style="background: #afcdf3;">

<div class="logo logo-inverted logo-tee" style="padding: 5em; max-width: 30em;">
  {% include 'ctflex/logo.svg' %}
</div>

</body>
</html>

django/ctflex/templates/ctflex/misc/winners.html
{% extends 'ctflex/base/headered.template.html' %}

{% block title %}
  Winners - {{ block.super }}
{% endblock %}

{% block header %}
  Winning Teams
{% endblock %}


{% block content %}
  <p>
    <emph>Information not available.</emph>
  </p>
{% endblock %}